# Generated by Django 6.0.1 on 2026-01-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.FloatField(help_text='Price per unit'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.FloatField(help_text='Available quantity in selected unit'),
        ),
    ]
