# Generated by Django 6.0.1 on 2026-01-14 05:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_crop_unit_alter_crop_price_alter_crop_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
